apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
namespace: dev
commonLabels:
  env: test
  version: "1.0"
configMapGenerator:
  - name: config-env
    env: env.env
  - name: config-properties
    files:
      - "application.properties"