apiVersion: v1
kind: Pod
metadata:
   name: ubuntu-sleepy
spec:
  containers:
  - name: k8s-4-developer
    image: k8s-4-developer
    args: ["100"]
    #command: ["echo"]
    resources:
      limits:
        cpu: 20Mi
        memory: 200Mi
      requests:
        cpu: 20Mi
        memory: 200Mi
