---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"

# ClusterIp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-cip
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080      # This should match the port you want to expose.
    protocol: TCP
    targetPort: 80  # This should match containerPort.
  selector:
    app: nginx
  #clusterIP: None   # This will create a headless service.
  
# Node Port

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: nginx
#   name: nginx-np
# spec:
#   type: NodePort                # Set the service type to NodePort
#   ports:
#   - name: http
#     port: 80                    # Service's port, accessed via NodePort
#     targetPort: 80              # Container's port (same as containerPort in Deployment)
#     protocol: TCP
#     nodePort: 32080             # Optional: specify a custom NodePort (must be between 30000-32767)
#   selector:
#     app: nginx

# Load Balancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx


# # ingress
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress-path
#   annotations:
#     #nginx.org/rewrites: 'serviceName=nginx-cip rewrite=/'
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: '*.foo.bar'
#       http:
#        paths:
#        - path: /
#          pathType: Prefix
#          backend:
#           service:
#             name: nginx-cip
#             port:
#               number: 8080
#        - path: /a
#          pathType: Prefix
#          backend:
#           service:
#             name: nginx-cip
#             port:
#               number: 8080
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress-domain
#   annotations:
#     #nginx.org/rewrites: 'serviceName=nginx-cip rewrite=/'
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: www.nginx-example.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx-cip
#             port:
#               number: 8080
#       - path: /nginx
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx-cip
#             port:
#               number: 8080