apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    type: fe
spec:
  template:
    metadata:
      name: nginx-pod
      labels: 
       app: nginx
       type: fe
    spec:
     containers:
     - name: nginx
       image: nginx
  replicas: 2
