apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-01
  name: ms-01
spec:
  type: NodePort
  ports:
  - name: "3000-tcp"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ms-01
