
worker_processes  5;  ## Default: 1
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024
}

http {
  index    index.html index.htm index.php;
  default_type application/octet-stream;
  
  sendfile     on;
  tcp_nopush   on;
  server_names_hash_bucket_size 128; # this seems to be required for some vhosts


  upstream ui_x {
    server ui:3000 weight=5;
  }

  upstream backend_x {
    server backend:3000 weight=5;
  }

  server {

    location / {
      proxy_pass      http://ui_x;
    }
    location /backend/ping {
      proxy_pass      http://backend_x/ping;
    }
    location /backend/info {
      proxy_pass      http://backend_x/info;
    }
  }
}