---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}-deployment
  labels:
    app: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      imagePullSecrets:
      - name: aks-registry-secret
      containers:
      - name: {{ .Values.name}}
        image: acr01azwe001.azurecr.io/demo/{{ .Values.image.name}}:{{ .Values.image.version}}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MESSAGE
          value: {{ .Values.message }}
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 1Gi