---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment-one
  labels:
    app: hello-world-one
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-one
  template:
    metadata:
      labels:
        app: hello-world-one
    spec:
      imagePullSecrets:
      - name: aks-registry-secret
      containers:
      - name: hello-world-one
        image: acr01azwe001.azurecr.io/demo/hello-world:20200810.4
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MESSAGE
          value: "deployment-1"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-one
spec:
  type: ClusterIP
  selector:
    app: hello-world-one
  ports:
    - name: hello-world-one-port
      port: 8080