# external dns
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ExternalName
  externalName: samit-nuc


# # external Ips
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
# spec:
#   selector:
#     app: MyApp
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 9376
#   externalIPs:
#     - 80.11.12.10