---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidecar-service
  name: sidecar-service
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
  selector:
    app: sidecar-ui
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidecar-backend
  name: backend
spec:
  ports:
  - name: "80"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sidecar-backend
  type: ClusterIP
  clusterIP: "None"